[workspace]
resolver = "2"
members = [
    "libs/backend/error-handler",
    "libs/backend/prisma-client",
    "libs/backend/session-manager",
    "apps/api",
    "apps/prisma-cli"
]

[workspace.dependencies]
backend_prisma_client = { path = "libs/backend/prisma-client"}
backend_session_manager = { path = "libs/backend/session-manager"}
backend_error_handler = { path = "libs/backend/error-handler"}
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", default-features = false, features=["postgresql", "rspc"], rev = "f210ca250c297b39b9bb23cb43bb3ab3712d4a4c"}
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", default-features = false, features=["postgresql", "rspc"], rev = "f210ca250c297b39b9bb23cb43bb3ab3712d4a4c"}
redis = {version = "^0.22", features = ["aio", "ahash", "tokio-comp"]}
tokio = { version = "^1.21", features = ["full"] }
openssl = { version = "^0.10", features = ["vendored"] } # daem openssl
