[workspace]
resolver = "2"
members = [
    "libs/backend/error-handler",
    "libs/backend/prisma-client",
    "libs/backend/session-manager",
    "apps/api",
    "apps/prisma-cli"
]

[workspace.dependencies]
backend_prisma_client = { path = "libs/backend/prisma-client"}
backend_session_manager = { path = "libs/backend/session-manager"}
backend_error_handler = { path = "libs/backend/error-handler"}
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", default-features = false, features=["postgresql"], rev = "a0fb19d25d6869c6398a338e5228d80c81a8c354"}
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", default-features = false, features=["postgresql"], rev = "a0fb19d25d6869c6398a338e5228d80c81a8c354"}
