[workspace]
resolver = "2"
members = [
    "apps/api",
    "apps/prisma-cli"
]

[workspace.dependencies]
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.2", default-features = false, features=["postgresql"]}
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.2", default-features = false, features=["postgresql"] }
