version: "3.9"
services:
  api:
    profiles: ["dev"]
    build:
      context: ./
      dockerfile: apps/api/Dockerfile
    ports:
      - "8000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/erudio?schema=public
      RUST_LOG: info,hyper=warn,tokio_postgres=info
      RUST_LOG_STYLE: always
      REDIS_URL: redis://127.0.0.1/
    depends_on:
      - db
      - red
  db:
    image: postgres:15.1
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: erudio
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest
    restart: unless-stopped
    network_mode: "host"
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
