version: "3.9"
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: erudio
      POSTGRES_PASSWORD: password