version: "3.9"
services:
  api:
    build:
      context: ./
      dockerfile: apps/api/Dockerfile
    ports:
      - "8000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/erudio?schema=public
      RUST_LOG: info,hyper=warn
      RUST_LOG_STYLE: always
    depends_on:
      - db
      - redis
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: erudio
      POSTGRES_PASSWORD: password
  redis:
    image: redis:7.0.5
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
