// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "public.version", input: never, result: string } | 
        { key: "super_admin.getSchool", input: GetSchoolRequest, result: School } | 
        { key: "super_admin.getUser", input: GetUserRequest, result: UserFull } | 
        { key: "super_admin.searchSchools", input: SearchSchoolsRequest, result: Array<School> } | 
        { key: "super_admin.searchSchoolsAmount", input: SearchSchoolsAmountRequest, result: number } | 
        { key: "super_admin.searchUsers", input: SearchUsersRequest, result: Array<UserFull> } | 
        { key: "super_admin.searchUsersAmount", input: SearchUsersAmountRequest, result: number } | 
        { key: "super_admin.version", input: never, result: string } | 
        { key: "user.me", input: never, result: UserMeResponse },
    mutations: 
        { key: "file.upload", input: UploadRequest, result: UploadResponse } | 
        { key: "public.login", input: LoginRequest, result: LoginResponse } | 
        { key: "public.login.admin", input: AdminLoginRequest, result: AdminLoginResponse } | 
        { key: "public.register", input: RegisterRequest, result: null } | 
        { key: "super_admin.addSchool", input: AddSchoolRequest, result: School } | 
        { key: "super_admin.addUserToSchool", input: AddUserToSchoolRequest, result: UserSchoolRelation } | 
        { key: "super_admin.updateSchool", input: UpdateSchoolRequest, result: School } | 
        { key: "user.logout", input: never, result: null },
    subscriptions: never
};

export interface AddSchoolRequest { idempotence_token: IdempotenceToken, name: string }

export interface AddUserToSchoolRequest { idempotence_token: IdempotenceToken, school_id: string, user_id: string, relation_type: SchoolRelationType }

export interface AdminLoginRequest { login: string, password: string }

export type AdminLoginResponse = { t: "Success" } | { t: "TwoFactorAuth", c: TwoFactorAuthType }

export interface GetSchoolRequest { id: string }

export interface GetUserRequest { id: string, school_id: string | null }

export type GrammaticalForm = "masculinine" | "feminine" | "indeterminate"

export interface IdempotenceToken { region: string, token: string }

export interface LoginRequest { email: string, password: string }

export type LoginResponse = { t: "Success" } | { t: "TwoFactorAuth", c: TwoFactorAuthType }

export interface Pagination { skip: number, take: number }

export interface PiiData { id: string, user_id: string, grammatical_form: GrammaticalForm, email: string | null, pesel: string | null, birth_date: string | null, legal_name: string, display_name: string, phone_prefix: string | null, phone_number: string | null, previous_data: any }

export interface RegisterRequest { idempotence_token: IdempotenceToken, email: string, password: string, first_name: string, middle_name: string | null, last_name: string, code: string | null }

export interface School { id: string, name: string, previous_data: any }

export type SchoolRelationType = "student" | "teacher" | "admin" | "director"

export interface SearchSchoolsAmountRequest { name: string }

export interface SearchSchoolsRequest { page: Pagination | null, name: string }

export interface SearchUsersAmountRequest { school_id: string, query: string }

export interface SearchUsersRequest { page: Pagination | null, school_id: string, query: string }

export interface TwoFactorAuthSettings { id: string, user_id: string, previous_data: any }

export type TwoFactorAuthType = "GoogleAuth" | "Sms" | "EMail"

export interface UpdateSchoolRequest { idempotence_token: IdempotenceToken, id: string, name: string | null }

export interface UploadRequest { idempotence_token: IdempotenceToken, idk: string }

export interface UploadResponse { presigned_url: string }

export interface UserMeResponse { id: string, display_name: string, school_relations: Array<[SchoolRelationType, string]> }

export interface UserSchoolRelation { user_id: string, school_id: string, school_relation_type: SchoolRelationType }

export interface UserFull { id: string, two_factor_auth_settings: TwoFactorAuthSettings | null, user_school_relation: Array<{ user_id: string, school_id: string, school_relation_type: SchoolRelationType, school: School }>, pii_data: PiiData | null }
