version: '3.9'
services:
  api:
    profiles: ['prod']
    build:
      context: ../..
      dockerfile: apps/erudio/backend-api/Dockerfile
      network: host
    network_mode: 'host'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:15.1
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - .env.postgress

  redis:
    image: redis:latest
    restart: unless-stopped
    network_mode: 'host'
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
