version: '3.9'
services:
  api:
    profiles: ['prod']
    build:
      context: ../..
      dockerfile: apps/erudio/backend-api/Dockerfile
      network: host
    network_mode: 'host'
    env_file:
      - ../../.env
    depends_on:
      - postgres
      - redis-stack-prod

  cocroach1:
    container_name: cockroach1
    hostname: cockroach1
    image: cockroachdb/cockroach:v22.2.3
    networks:
      - roachnet
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start --insecure --advertise-addr=cockroach1:26257
    volumes:
      - "roach1:/cockroach/cockroach-data:rw"
  cocroach2:
    container_name: cockroach2
    hostname: cockroach2
    image: cockroachdb/cockroach:v22.2.3
    networks:
      - roachnet
    ports:
      - "8081:8080"
    command: start --insecure --join=cockroach1:26257
    volumes:
      - "roach2:/cockroach/cockroach-data:rw"
  cocroach3:
    container_name: cockroach3
    hostname: cockroach3
    image: cockroachdb/cockroach:v22.2.3
    networks:
      - roachnet
    ports:
      - "8082:8080"
    command: start --insecure --join=cockroach1:26257
    volumes:
      - "roach3:/cockroach/cockroach-data:rw"

  redis-stack:
    profiles: ['']
    image: redis/redis-stack:latest
    restart: unless-stopped
    network_mode: 'host'
    command: redis-server /etc/redis-stack.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
      - redis_data:/data:rw

  redis-stack-prod:
    profiles: ['prod']
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    network_mode: 'host'
    command: redis-server /etc/redis-stack.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
      - redis_data:/data:rw

  nginx:
    image: nginx
    restart: unless-stopped
    network_mode: 'host'
    volumes:
      - ./docker/nginx/:/etc/nginx/
      - ./frontend/dist/public:/www/data

  fluentbit:
    image: fluent/fluent-bit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    restart: unless-stopped
    network_mode: 'host'
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf


volumes:
  redis_data:
  roach1:
  roach2:
  roach3:

networks:
  roachnet: