version: '3.9'
services:
  api:
    profiles: ['prod']
    build:
      context: ../..
      dockerfile: apps/erudio/backend-api/Dockerfile
      network: host
    network_mode: 'host'
    env_file:
      - ../../.env
    depends_on:
      - postgres
      - redis-stack-prod
  postgres:
    image: postgres:15.1
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - ../../.env.postgress

  redis-stack:
    profiles: ['']
    image: redis/redis-stack:latest
    restart: unless-stopped
    network_mode: 'host'
    command: redis-server /etc/redis-stack.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
      - redis_data:/data:rw

  redis-stack-prod:
    profiles: ['prod']
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    network_mode: 'host'
    command: redis-server /etc/redis-stack.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
      - redis_data:/data:rw

  nginx:
    image: nginx
    restart: unless-stopped
    network_mode: 'host'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  fluentbit:
    image: fluent/fluent-bit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    restart: unless-stopped
    network_mode: 'host'
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf


volumes:
  redis_data: