// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pl'

export type Locales =
	| 'de'
	| 'en'
	| 'pl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * C​z​e​ś​ć​ ​{​n​a​m​e​}​!
	 * @param {unknown} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * E​m​a​i​l
	 */
	EMAIL: string
	/**
	 * H​a​s​ł​o
	 */
	PASSWORD: string
	/**
	 * Z​a​l​o​g​u​j​ ​s​i​ę
	 */
	LOGINBUTTON: string
	/**
	 * N​i​e​p​r​a​w​i​d​ł​o​w​e​ ​d​a​n​e​ ​l​o​g​o​w​a​n​i​a
	 */
	INVALIDLOGIN: string
}

export type TranslationFunctions = {
	/**
	 * Cześć {name}!
	 */
	HI: (arg: { name: unknown }) => LocalizedString
	/**
	 * Email
	 */
	EMAIL: () => LocalizedString
	/**
	 * Hasło
	 */
	PASSWORD: () => LocalizedString
	/**
	 * Zaloguj się
	 */
	LOGINBUTTON: () => LocalizedString
	/**
	 * Nieprawidłowe dane logowania
	 */
	INVALIDLOGIN: () => LocalizedString
}

export type Formatters = {}
