// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "public.login", input: LoginRequest, result: LoginResponse } | 
        { key: "public.version", input: never, result: string } | 
        { key: "user.me", input: never, result: { two_factor_auth_settings: { placeholder_field: string } | null, pii_data: { grammatical_form: GrammaticalForm, email: string | null, pesel: string | null, birth_date: string | null, legal_name: string | null, display_name: string | null, phone_prefix: string | null, phone_number: string | null } | null, user_school_relation: Array<{ school: { name: string, previus_data: Array<any>, school_settings: { previus_data: Array<any> } | null } }> } },
    mutations: 
        { key: "public.register", input: RegisterRequest, result: null },
    subscriptions: never
};

export type GrammaticalForm = "masculinine" | "feminine" | "indeterminate"

export interface LoginRequest { email: string, password: string }

export type LoginResponse = { t: "Success" } | { t: "TwoFactorAuth", c: TwoFactorAuthType }

export interface RegisterRequest { email: string, password: string, code: null }

export type TwoFactorAuthType = "GoogleAuth" | "Sms" | "EMail"
