// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
  queries:
    | { key: 'public.login'; input: LoginRequest; result: LoginResponse }
    | { key: 'public.register'; input: RegisterRequest; result: null }
    | { key: 'public.version'; input: never; result: string };
  mutations: never;
  subscriptions: never;
};

export interface LoginRequest {
  email: string;
  password: string;
}

export type LoginResponse =
  | { t: 'Success' }
  | { t: 'TwoFactorAuth'; c: TwoFactorAuthType };

export interface RegisterRequest {
  email: string;
  password: string;
  code: null;
}

export type TwoFactorAuthType = 'GoogleAuth' | 'SMS' | 'EMail';
