[package]
name = "api_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prisma-client-rust.workspace = true
prisma-client-rust-cli.workspace = true
tokio = { version= "^1", features=["full"]}
serde = {version = "^1", features=["derive"]}
dotenv = "^0"