// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pl'

export type Locales =
	| 'de'
	| 'en'
	| 'pl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	index: {
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * H​a​s​ł​o
		 */
		password: string
		/**
		 * Z​a​l​o​g​u​j​ ​s​i​ę
		 */
		login: string
		/**
		 * N​i​e​p​r​a​w​i​d​ł​o​w​e​ ​d​a​n​e​ ​l​o​g​o​w​a​n​i​a
		 */
		invalid: string
		/**
		 * T​r​y​b​ ​c​i​e​m​n​y
		 */
		darkMode: string
	}
	dashboard: {
		/**
		 * N​a​u​c​z​y​c​i​e​l
		 */
		teacher: string
		/**
		 * U​c​z​e​ń
		 */
		student: string
		/**
		 * A​d​m​i​n​i​s​t​r​a​t​o​r
		 */
		admin: string
		/**
		 * D​y​r​e​k​t​o​r
		 */
		director: string
	}
}

export type TranslationFunctions = {
	index: {
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Hasło
		 */
		password: () => LocalizedString
		/**
		 * Zaloguj się
		 */
		login: () => LocalizedString
		/**
		 * Nieprawidłowe dane logowania
		 */
		invalid: () => LocalizedString
		/**
		 * Tryb ciemny
		 */
		darkMode: () => LocalizedString
	}
	dashboard: {
		/**
		 * Nauczyciel
		 */
		teacher: () => LocalizedString
		/**
		 * Uczeń
		 */
		student: () => LocalizedString
		/**
		 * Administrator
		 */
		admin: () => LocalizedString
		/**
		 * Dyrektor
		 */
		director: () => LocalizedString
	}
}

export type Formatters = {}
