name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0


  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./apps/erudio/docker-compose.yml"
          services: |
            postgres
            db
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose


  integration:
    runs-on: ubuntu-latest
    needs:
      - frontend
      - backend
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0