name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.8
    with:
      number-of-agents: 3
      parallel-commands: |
        pnpx nx-cloud record -- pnpx nx workspace-lint
        pnpx nx-cloud record -- pnpx nx format:check
      parallel-commands-on-agents: |
        pnpx nx affected --target=lint --parallel=3 & pnpx nx affected --target=test --parallel=3 --ci --code-coverage & pnpx nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.8
    with:
      number-of-agents: 3
