name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: pnpm ci

      - run: pnpx nx workspace-lint
      - run: pnpx nx format:check
      - run: pnpx nx affected --target=lint --parallel=3
      - run: pnpx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: pnpx nx affected --target=build --parallel=3
