name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  frontend-changes:
    runs-on: ubuntu-latest
    outputs:
      found: ${{ steps.changed-frontend.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed frontend files
        id: changed-frontend
        uses: tj-actions/changed-files@v34
        with:
          files: |
            **/*.{json, js, ts, jsx, tsx, html, css}

  frontend:
    runs-on: ubuntu-latest
    needs: frontend-changes
    if: needs.frontend-changes.outputs.found == 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

  backend-changes:
    runs-on: ubuntu-latest
    outputs:
      found: ${{ steps.changed-rust.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed rust files
        id: changed-rust
        uses: tj-actions/changed-files@v34
        with:
          files: |
            **/*.{rs, toml}
    

  backend:
    runs-on: ubuntu-latest
    needs: backend-changes
    if: needs.backend-changes.outputs.found == 'true'
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          # - stable - not suported #![feature(future_join)]
          # - beta - not supported  #![feature(future_join)]
          - nightly
        environment: [dev] # test, staging, production
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: cp -a ./envs/${{ matrix.environment }}/. .
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./apps/erudio/docker-compose.yml"
          services: |
            postgres
            redis
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy
      - uses: Swatinem/rust-cache@v2
      - name: Generate prisma client
        run: cargo run --bin prisma_cli --release -- generate
        working-directory: ./apps/erudio/backend-prisma-cli
      - run: cargo build --release
      - run: cargo clippy --release -- -D warnings
      - run: cargo test --release


  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev] # test, staging, production
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed code files
        id: changed-any
        uses: tj-actions/changed-files@v34
        with:
          files: |
            **/*.{rs, toml, json, yaml, js, ts, jsx, tsx, html, css}
            ./apps/erudio/docker-compose.yml
      - run: cp -a ./envs/${{ matrix.environment }}/. .
        if: steps.changed-any.outputs.any_changed == 'true'
      - run: docker-compose pull
        if: steps.changed-any.outputs.any_changed == 'true'
        working-directory: ./apps/erudio
      - uses: isbang/compose-action@v1.4.1
        if: steps.changed-any.outputs.any_changed == 'true'
        with:
          compose-file: "./apps/erudio/docker-compose.yml"
          up-flags: "--build"
          services: |
            postgres
            redis
            api
      - run: echo "INTEGRATION TESTS"
        if: steps.changed-any.outputs.any_changed == 'true'
