name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0


  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./apps/erudio/docker-compose.ci.yml"
          services: |
            postgres
            redis
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Generate prisma client
        run: cargo prisma generate
        working-directory: ./apps/erudio/backend-prisma-cli
      - run: cargo build
      - run: cargo clippy -- -D warnings
      - run: cargo test


  integration:
    runs-on: ubuntu-latest
    needs:
      - frontend
      - backend
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0